//
//  currencies.swift
//  MoneyPlant App
//
//  Created by admin15 on 22/12/24.
//

import Foundation

let currencies = [
    "USD - United States Dollar",
    "INR - Indian Rupee",
    "EUR - Euro",
    "JPY - Japanese Yen",
    "GBP - British Pound Sterling",
    "AUD - Australian Dollar",
    "CAD - Canadian Dollar",
    "CHF - Swiss Franc",
    "CNY - Chinese Yuan Renminbi",
    "SEK - Swedish Krona",
    "NZD - New Zealand Dollar",
    "MXN - Mexican Peso",
    "SGD - Singapore Dollar",
    "HKD - Hong Kong Dollar",
    "NOK - Norwegian Krone",
    "KRW - South Korean Won",
    "TRY - Turkish Lira",
    "RUB - Russian Ruble",
    "BRL - Brazilian Real",
    "ZAR - South African Rand",
    "PHP - Philippine Peso",
    "IDR - Indonesian Rupiah",
    "THB - Thai Baht",
    "MYR - Malaysian Ringgit",
    "VND - Vietnamese Dong",
    "SAR - Saudi Riyal",
    "AED - UAE Dirham",
    "PLN - Polish Zloty",
    "ILS - Israeli New Shekel",
    "DKK - Danish Krone",
    "HUF - Hungarian Forint",
    "CZK - Czech Koruna",
    "CLP - Chilean Peso",
    "PKR - Pakistani Rupee",
    "BDT - Bangladeshi Taka",
    "EGP - Egyptian Pound",
    "KWD - Kuwaiti Dinar",
    "NGN - Nigerian Naira",
    "TWD - New Taiwan Dollar",
    "QAR - Qatari Riyal",
    "OMR - Omani Rial",
    "COP - Colombian Peso",
    "ARS - Argentine Peso",
    "JMD - Jamaican Dollar",
    "KES - Kenyan Shilling",
    "UGX - Ugandan Shilling",
    "TZS - Tanzanian Shilling",
    "GHS - Ghanaian Cedi",
    "XAF - Central African CFA Franc",
    "XOF - West African CFA Franc",
    "MAD - Moroccan Dirham",
    "DZD - Algerian Dinar",
    "BHD - Bahraini Dinar",
    "LKR - Sri Lankan Rupee",
    "MUR - Mauritian Rupee",
    "ETB - Ethiopian Birr",
    "ZMW - Zambian Kwacha",
    "MWK - Malawian Kwacha",
    "BWP - Botswana Pula"
]
